apiVersion: v1
kind: Service
metadata:
  name: bootcamp
  labels:
    app: bootcamp
spec:
    #type: NodePort
  ports:
  - port: 8080
    #targetPort: 8080
    #name: http
    #protocol: TCP
  selector:
    app: bootcamp
